---
title: "Scoring cells singscore"
author: "Abinet Joan"
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output:
  pdf_document: 
    toc: true
    toc_depth: 2
  html_document: default
header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading package
```{r}
suppressMessages(library(dplyr))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(readxl))
suppressMessages(library(singscore))
suppressMessages(library(pheatmap))
```

# Loading the normalised count matrix
```{r}
Norm_exprMat <- read_excel("../Data_Thomas/Q3 - publication - V2.xlsx", sheet = "TargetCountMatrix")
Norm_exprMat <- as.data.frame(Norm_exprMat)
rownames(Norm_exprMat) <- Norm_exprMat$TargetName
Norm_exprMat$TargetName <- NULL
```

# Score sample with singscore

## Get score Motro
```{r}
Motro_DE <- read.csv("myeloids_markers_top20.csv")

Motro_DE <- Motro_DE[Motro_DE$cluster == 1,]
Top20_Motro <- Motro_DE$gene

rankData <- rankGenes(Norm_exprMat)
scoredf <- simpleScore(rankData, upSet = Top20_Motro)

Motro <- scoredf$TotalScore
```

## Get score AM
```{r}
myeloid.markers <- read.csv("myeloids_markers_top20.csv")

myeloid.markers_AM <- myeloid.markers[myeloid.markers$cluster == 5,]$gene

# Ear2 and Kcnq1ot1 are not in the expression data 
myeloid.markers_AM <- myeloid.markers_AM[-c(7,13)]

rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = myeloid.markers_AM)
AM <- scoredf$TotalScore

cell_singscore <- data.frame(Motro, AM)
```

## Get score neutro
```{r}
myeloid.markers_neut <- myeloid.markers[myeloid.markers$cluster == 6,]$gene

# Stfa2l1 and Cstdc4 are not in the expression data 
myeloid.markers_neut <- myeloid.markers_neut[-c(5,8)]

rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = myeloid.markers_neut)
cell_singscore <- cbind(cell_singscore, Neutro = scoredf$TotalScore)
```

## Get score cd64
```{r}
myeloid.markers_cd64 <- myeloid.markers[myeloid.markers$cluster == 4,]$gene

# Ly6c2 and Ifi204 are not in the expression data 
myeloid.markers_cd64 <- myeloid.markers_cd64[-c(2,12)]

rankData <- rankGenes(Norm_exprMat)
scoredf <- simpleScore(rankData, upSet = myeloid.markers_cd64)

cell_singscore <- cbind(cell_singscore, cd64 = scoredf$TotalScore)
```

## Get score CD206- IM
```{r}
myeloid.markers_IM <- myeloid.markers[myeloid.markers$cluster == 0,]$gene

rankData <- rankGenes(Norm_exprMat)
scoredf <- simpleScore(rankData, upSet = myeloid.markers_IM)

cell_singscore <- cbind(cell_singscore, "CD206- IM" = scoredf$TotalScore)
```

## Get score CD206+ IM
```{r}
myeloid.markers_CD206 <- myeloid.markers[myeloid.markers$cluster == 7,]$gene

rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = myeloid.markers_CD206)

cell_singscore <- cbind(cell_singscore, "CD206+ IM" = scoredf$TotalScore)
```


# Write csv file for singscore
```{r}
rownames(cell_singscore) <- colnames(Norm_exprMat)

#write.csv(cell_singscore, "cell_singscore.csv")
```


# plotting score in pheatmap
```{r fig.width=8, fig.height=5}
annotation_sample <- read_excel("../Data_Thomas/Q3 - publication - V2.xlsx", sheet = "SegmentProperties")
singscores <- cell_singscore
singscores <- merge(singscores, annotation_sample[,c(5,25)], by.x = "row.names", by.y = "SegmentDisplayName")
singscores <- singscores[order(singscores$Group),]
singscores$Group<- NULL

rownames(singscores) <- singscores$Row.names
singscores$Row.names <- NULL

df <- as.data.frame(annotation_sample[,c(5,25)])
df$Group <- as.factor(df$Group)
levels(df$Group) <- c("Control", "Intralesional", "Perilesional", "Extralesional")
rownames(df)<-df$SegmentDisplayName
df$SegmentDisplayName <- NULL


pheatmap_singscore<- pheatmap(t(singscores), cluster_rows=FALSE, show_rownames=T,
         cluster_cols=F, scale = "row", annotation_col=df, main = "Singscores", labels_row = c("Ly6G Macs", "AM", "Neutro", "CD64+ Mono", "CD206- IM", "CD206+ IM" ), color = colorRampPalette(c("blue", "white", "red"))(100))
```

```{r}
sessionInfo()
```


