---
title: "Scoring cell"
author: "Abinet Joan"
date: "3/2/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
suppressMessages(library(dplyr))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(DESeq2))
suppressMessages(library(readxl))
suppressMessages(library("pheatmap"))
suppressMessages(library("RColorBrewer"))
```


# Loading transptomic spatial data
```{r pressure, echo=FALSE}
setwd("~/Documents/Travail_cell/Travail_V3/Project_cecilia/Transcriptomique_spatiale/Info_sample+data")

countData <- read_excel("All Data WTA.xlsx", sheet = "Q3")
countData <- as.data.frame(countData)

# get gene name as row name
rownames(countData) <- countData$TargetName
countData <- countData[,-1]
# Arrondir les valeurs car nécessite des int
countData <- round(countData)


colData <- read.table("reference_sample.txt", header= T, sep = ",")
# transforme les noms de rangé de colData
rownames(colData) <- colData[,1]

dds_Q3 <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ Slice + Analyse_DE)

dds_Q3 <- DESeq(dds_Q3)
rlogQ3<- rlog(dds_Q3)
```


## score AM
```{r}
myeloid.markers <- read.csv("/home/qiang/Documents/Travail_cell/Travail_V3/Cécilia_project_2/1.2Visualise_feature/myeloids_markers_top20.csv")

myeloid.markers_AM <- myeloid.markers[myeloid.markers$cluster == 5,]$gene

# Ear2 and Kcnq1ot1 are not in the expression data 
myeloid.markers_AM <- myeloid.markers_AM[-c(7,13)]

#myeloid.markers_AM <- "Plet1"

# Get expression assays
Norm_exprMat <- assay(rlogQ3)
Norm_exprMat2 <- counts(dds_Q3, normalized=T)
Norm_exprMat <- Norm_exprMat2
# get mean value by row
data.avg <- Matrix::rowMeans(x = Norm_exprMat)

# Order genes from lowest to highest mean by row
data.avg <- data.avg[order(data.avg)]

# the value of nbin is 25 by default
nbin <- 25
# create 25 groups of genes. Allows to associateas control genes, genes that are specific
data.cut <- ggplot2::cut_number(x = data.avg + rnorm(n = length(data.avg))/1e+30,
                                n = nbin,
                                labels = FALSE,
                                right = FALSE)


# Set the names of the cuts as the gene names
names(x = data.cut) <- names(x = data.avg)
data.cut # les gènes sont mtn classé en fct° de leur expression moyenne.

# Create an empty list the same length as the number of input gene sets. This will contain the names of the control genes
cluster.length <- 1 # toujours placé à 1 car on ne teste que un seul geneset
ctrl.use <- vector(mode = "list", length = cluster.length) # cluster.length = nbre de gène qu'on va regarder ici 20


features <- list(myeloid.markers_AM)
ctrl <- 100 # paramètres de base

# For each of the input gene lists:
for (i in 1:cluster.length) {
  # Get the gene names from the input gene set as a character vector  
  features.use <- features[[i]]
  
  # Loop through the provided genes (1:num_genes) and for each gene, find ctrl (default=100) genes from the same expression bin (by looking in data.cut):
  for (j in 1:length(x = features.use)) {
        # Within this loop, 'data.cut[features.use[j]]' gives us the expression bin number. We then sample `ctrl` genes from that bin without replacement and add the gene names to ctrl.use.
        ctrl.use[[i]] <- c(ctrl.use[[i]],
                           names(x = sample(x = data.cut[which(x = data.cut == data.cut[features.use[j]])],
                                            size = ctrl, # sélectionne des gènes faisant partie du même bin que celui
                                            replace = FALSE)))
    }
}

length(ctrl.use[[1]])
```

# Visualisation des gènes
```{r}
plot(data.avg, pch=16, ylab="Average expression across all cells", xlab="All genes, ranked")
for(i in unique(data.cut)){
cut_pos <- which(data.cut==i)
if(i%%2==0){
  rect(xleft = cut_pos[1], ybottom = min(data.avg), xright = cut_pos[length(cut_pos)], ytop = max(data.avg), col=scales::alpha("grey", 0.3))
} else {
  rect(xleft = cut_pos[1], ybottom = min(data.avg), xright = cut_pos[length(cut_pos)], ytop = max(data.avg), col=scales::alpha("white", 0.3))
}
}

# Add red points for selected control genes
points(which(names(data.avg)%in%ctrl.use[[1]]), data.avg[which(names(data.avg)%in%ctrl.use[[1]])], pch=16, col="red")

# Add blue points for genes in the input gene list
points(which(names(data.avg)%in%features[[1]]), data.avg[which(names(data.avg)%in%features[[1]])], pch=16, col="blue")

# Add a legend
legend(x = "topleft",
       legend = c("gene", "selected control gene", "gene in geneset"),
       col = c("black", "red", "blue"),
       pch = 16)
```


# Calcul de l'expression moyenne des gènes ctrl.
```{r}
# On place tous nos gènes ctrl dans une matrice
ctrl.scores <- matrix(data = numeric(length = 1L),
                      nrow = length(x = ctrl.use),
                      ncol = 24) # 24 correspond au nombre d'échantillons

assay.data <- assay(rlogQ3)

# Calcule la moyenne des valeurs 100 gènes ctrl pour chacun des 20 gènes motro et chaque échantillons
for (i in 1:length(ctrl.use)) {
  
  # Get control gene names as a vector  
  features.use <- ctrl.use[[i]]
  # For each cell, calculate the mean expression of *all* of the control genes 
  ctrl.scores[i,] <- Matrix::colMeans(x = assay.data[features.use,])
}
```

# Calcule de l'expression moyenne des gènes AM
```{r}
features.scores <- matrix(data = numeric(length = 1L),
                          nrow = cluster.length,
                          ncol = 24)

# Loop through input gene sets and calculate the mean expression of these genes for each cell
for (i in 1:cluster.length) {
    features.use <- features[[i]]
    data.use <- assay.data[features.use, , drop = FALSE]
    features.scores[i, ] <- Matrix::colMeans(x = data.use) # cette formulation est stupide car je calcule la moyenne d'un seul élément (mais ça marche je précise)
}
```

# plot score
```{r}
features.scores.use <- features.scores - ctrl.scores

data_plot <- cbind(colData(rlogQ3),as.vector(features.scores.use))
data_plot <- data_plot[order(data_plot$Position),]

barplot(data_plot$`as.vector(features.scores.use)`,
        col = c(rep("orange",2), rep("red",2) , rep("green",4), rep("cyan",6) ,rep("blue",8), rep("pink",2)),
        
        names.arg = c("1_1","2_1","1_2","2_2","1_6","1_9","2_3","2_8","1_3","1_5","1_8","2_12", "2_4", "2_5", "1_10", "1_11", "1_4", "1_7", "2_10", "2_11", "2_6", "2_7", "1_12", "2_9")
)

```

```{r}
myeloid.markers_AM

plotCounts(dds_Q3, gene= "Plet1", intgroup = "SegmentDisplayName", returnData = T)

d <- plotCounts(dds_Q3, gene= "Plet1", intgroup="SegmentDisplayName", returnData = T, transform = F)
ggplot(d, aes(x=SegmentDisplayName, y=count)) + 
  geom_point(position=position_jitter(w=0.1,h=0)) + 
  scale_y_log10(breaks=c(25,100,400))

```

```{r}
sessionInfo()
```


```{r}
library(singscore)
library(GSEABase)

rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = myeloid.markers_AM)

scoredf
scoredf <- cbind(colData(rlogQ3)$Position,scoredf)
scoredf <- scoredf[order(scoredf$`colData(rlogQ3)$Position`),]

barplot(scoredf$TotalScore,
        col = c(rep("orange",2), rep("red",2) , rep("green",4), rep("cyan",6) ,rep("blue",8), rep("pink",2)),
        
        names.arg = c("1_1","2_1","1_2","2_2","1_6","1_9","2_3","2_8","1_3","1_5","1_8","2_12", "2_4", "2_5", "1_10", "1_11", "1_4", "1_7", "2_10", "2_11", "2_6", "2_7", "1_12", "2_9")
)
```

# je réessaye avec un score motro
```{r}
Motro_DE <- read.csv("/home/qiang/Documents/Travail_cell/Travail_V3/Project_cecilia/4GO_Scenic/signature_motro_DE.csv")
Motro_DE <- Motro_DE[order(Motro_DE$avg_log2FC, decreasing = T),]
Top20_Motro <- Motro_DE$X[1:20]


rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = Top20_Motro)

scoredf
scoredf <- cbind(colData(rlogQ3)$Position,scoredf)
scoredf <- scoredf[order(scoredf$`colData(rlogQ3)$Position`),]

barplot(scoredf$TotalScore,
        col = c(rep("orange",2), rep("red",2) , rep("green",4), rep("cyan",6) ,rep("blue",8), rep("pink",2)),
        
        names.arg = c("1_1","2_1","1_2","2_2","1_6","1_9","2_3","2_8","1_3","1_5","1_8","2_12", "2_4", "2_5", "1_10", "1_11", "1_4", "1_7", "2_10", "2_11", "2_6", "2_7", "1_12", "2_9"), ylim = c(0,0.5)
)
```

# score bronchovascular
```{r}
sig_broncho <- c("Scgb3a2","Cbr2","Cyp2f2","Scgb1a1")
rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = sig_broncho)

scoredf
scoredf <- cbind(colData(rlogQ3)$Position,scoredf)
scoredf <- scoredf[order(scoredf$`colData(rlogQ3)$Position`),]

barplot(scoredf$TotalScore,
        col = c(rep("orange",2), rep("red",2) , rep("green",4), rep("cyan",6) ,rep("blue",8), rep("pink",2)),
        
        names.arg = c("1_1","2_1","1_2","2_2","1_6","1_9","2_3","2_8","1_3","1_5","1_8","2_12", "2_4", "2_5", "1_10", "1_11", "1_4", "1_7", "2_10", "2_11", "2_6", "2_7", "1_12", "2_9")
)
```

```{r}
features.scores.use <- GetSignatureScore(dds_Q3, sig_broncho)

visualise_score(features.scores.use)
```

