---
title: "Spatial Decon"
author: "Abinet Joan"
date: "4/20/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
suppressMessages(library(dplyr))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(DESeq2))
suppressMessages(library(readxl))
suppressMessages(library("pheatmap"))
suppressMessages(library("RColorBrewer"))
suppressMessages(library(singscore))
suppressMessages(library(SpatialDecon))

suppressMessages(library(Cellpr))
```

# Loading transptomic spatial data and generating deseq2 object
```{r pressure, echo=FALSE}
setwd("~/Documents/Travail_cell/Travail_V3/Project_cecilia/Transcriptomique_spatiale/Info_sample+data")

countData <- read_excel("All Data WTA.xlsx", sheet = "Q3")
countData <- as.data.frame(countData)

# get gene name as row name
rownames(countData) <- countData$TargetName
countData <- countData[,-1]
# Arrondir les valeurs car nécessite des int
countData <- round(countData)


colData <- read.table("reference_sample.txt", header= T, sep = ",")
# transforme les noms de rangé de colData
rownames(colData) <- colData[,1]

dds_Q3 <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ Slice + Analyse_DE)

dds_Q3 <- suppressMessages(DESeq(dds_Q3))
rlogQ3<- suppressMessages(rlog(dds_Q3))


```

# Apparté comparaison des données
```{r}
View(counts(dds_Q3,normalized=TRUE))
setwd("~/Documents/Travail_cell/Travail_V3/Project_cecilia/Transcriptomique_spatiale/Info_sample+data")
View(read_excel("All Data WTA.xlsx", sheet = "Q3"))
```

All profile matrix can be seen at https://github.com/Nanostring-Biostats/CellProfileLibrary/tree/NewProfileMatrices

# download profile matrix for lung immune dataset
```{r}
load("profile_matrix/Lung_MCA.RData")
write.csv(x = profile_matrix, file = "profile_matrix/matrixName.csv", 
          row.names = TRUE, quote = FALSE)

lung_data <- download_profile_matrix("Lung_plus_neutrophils")
```

```{r}
setwd("~/Documents/Travail_cell/Travail_V3/Project_cecilia/Transcriptomique_spatiale/Info_sample+data")
countData <- read_excel("All Data WTA.xlsx", sheet = "Q3")

countData <- as.data.frame(countData)
rownames(countData) <- countData$TargetName
countData <- countData[,-1]

# estimate background:
bg <- derive_GeoMx_background(
  norm = countData,
  probepool = rep(1, nrow(countData)),
  negnames = "NegProbe-WTX" # j'ai adapté par une des rangés de countData, je sais pas si c'est bon.
)

# use the NegProbe to estimate per-observation background
per.observation.mean.neg = countData["NegProbes-WTX", ]
# and define a background matrix in which each column (observation) is the
# appropriate value of per-observation background:
bg = sweep(countData * 0, 2, per.observation.mean.neg, "+")
dim(bg)

countData <- as.data.frame(countData)

# run basic decon:
res = spatialdecon(norm = as.matrix(countData),
                   bg = bg,
                   X = as.matrix(profile_matrix),
                   align_genes = TRUE)

str(res)
# res$beta: estimated of matrix abundance
heatmap(res$beta, cexCol = 0.9, cexRow = 0.7, margins = c(10,7))


# how to visualise
mat_res <- res$beta
keep <- rowSums(res$beta) > 1
mat_res <- mat_res[keep,]
pheatmap(mat_res, scale = "row")

pheatmap(mat_res)
```

# Cell abundance estimates
Using the advanced settings of spatialdecon
```{r}
# loading raw data
setwd("~/Documents/Travail_cell/Travail_V3/Project_cecilia/Transcriptomique_spatiale/Info_sample+data")
rawData <- read_excel("All Data WTA.xlsx", sheet = "Probe QC")
rawData <- as.data.frame(rawData)
rownames(rawData) <- rawData$TargetName
rawData <- rawData[,-1]

# loading annotation
setwd("~/Documents/Travail_cell/Travail_V3/Project_cecilia/Transcriptomique_spatiale/Info_sample+data")
annot <- read_excel("All Data WTA.xlsx", sheet = "SegmentProperties")

annot <- annot[order(annot$SegmentDisplayName),] # je pense qu'il faut que l'ordre des samples correspondes
annot$AOINucleiCount

restils = spatialdecon(norm = as.matrix(countData),                     # normalized data
                       raw = as.matrix(rawData),                       # raw data, used to down-weight low-count observations 
                       bg = bg,                         # expected background counts for every data point in norm
                       X = as.matrix(profile_matrix),                     # safeTME matrix, used by default
                       cell_counts = annot$AOINucleiCount)   


mat_res <- restils$beta
keep <- rowSums(restils$beta) > 1
mat_res <- mat_res[keep,]
pheatmap(mat_res, scale = "row")
```

