---
title: "GSEA output"
author: "Abinet Joan"
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output:
  pdf_document: default
  html_document: default
header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Package
```{r}
suppressMessages(library(ggplot2))
suppressMessages(library("forcats"))
```

# Modify dataframe format
```{r}
modify_GSEA_data <- function(GSEA_results){
  GSEA_results<- GSEA_results[order(GSEA_results$NES, decreasing = T),]
  GSEA_results <- GSEA_results[1:20,]
  
  # define the column has a factor so that the order of Ontology is maintain in the plot.
  GSEA_results$NAME <- factor(GSEA_results$NAME, levels = GSEA_results$NAME)
  GSEA_results$NAME <- fct_rev(GSEA_results$NAME) 
  
  GSEA_results
}
```

# Creating Dotplot for BP results
```{r}
dir <- "GSEA_Output/"
GSEA_BP_res <- read.table(paste0(dir,"my_analysis.Gsea.1675247466167_BP/gsea_report_for_2_1675247466167.tsv"), header = T, sep = "\t")

GSEA_BP_res <- modify_GSEA_data(GSEA_BP_res)

GSEA_BP_res$NAME <- substring(GSEA_BP_res$NAME, 6)
GSEA_BP_res$NAME <- gsub("_", " ", GSEA_BP_res$NAME)

GSEA_BP_res$NAME <- fct_rev(factor(GSEA_BP_res$NAME, levels = GSEA_BP_res$NAME))
```

```{r fig.width=10, fig.height=5}
ggplot(GSEA_BP_res, aes(x = NES,y =NAME, size = SIZE, color = FDR.q.val)) + geom_point() + ggtitle("GSEA - Biological Pathways") + scale_color_gradient(low = "red", high = "blue") + theme_bw()+ scale_size(range = c(3,10))
#ggsave("plot_result/GSEA_results_BP_céci2.pdf", width = 12, height = 8)
```

# Creating Dotplot for CC results
```{r}
GSEA_CC_res <- read.table(paste0(dir,"my_analysis.Gsea.1675339652585_CC/gsea_report_for_2_1675339652585.tsv"), header = T, sep = "\t")

GSEA_CC_res <- modify_GSEA_data(GSEA_CC_res)

GSEA_CC_res <- GSEA_CC_res[1:15,]

GSEA_CC_res$NAME <- substring(GSEA_CC_res$NAME, 6)
GSEA_CC_res$NAME <- gsub("_", " ", GSEA_CC_res$NAME)
GSEA_CC_res$NAME <- fct_rev(factor(GSEA_CC_res$NAME, levels = GSEA_CC_res$NAME))
```

```{r fig.width=10, fig.height=5}
ggplot(GSEA_CC_res, aes(x = NES,y =NAME, size = SIZE, color = FDR.q.val)) + geom_point() + ggtitle("GSEA - Cellular Components") + scale_color_gradient(low = "red", high = "blue") + theme_bw() + scale_size(range = c(3,10))
#ggsave("plot_result/GSEA_results_CC_céci2.pdf", width = 12, height = 8)
```


# Creating Dotplot for BP results
```{r}
GSEA_MF_res <- read.table(paste0(dir,"my_analysis.Gsea.1675341806364_MF/gsea_report_for_2_1675341806364.tsv"), header = T, sep = "\t")

GSEA_MF_res <- modify_GSEA_data(GSEA_MF_res)

GSEA_MF_res$NAME <- substring(GSEA_MF_res$NAME, 6)
GSEA_MF_res$NAME <- gsub("_", " ", GSEA_MF_res$NAME)

GSEA_MF_res$NAME <- fct_rev(factor(GSEA_MF_res$NAME, levels = GSEA_MF_res$NAME))
```

```{r fig.width=10, fig.height=5}
ggplot(GSEA_MF_res, aes(x = NES,y =NAME, size = SIZE, color = FDR.q.val)) + geom_point() + ggtitle("GSEA - Molecular Function") + scale_color_gradient(low = "red", high = "blue") + theme_bw()+ scale_size(range = c(3,10))
#ggsave("plot_result/GSEA_results_MF_céci2.pdf", width = 12, height = 8)
```


```{r}
sessionInfo()
```
