---
title: "Scoring human Macrophages"
author: "Abinet Joan"
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output:
  pdf_document:  
    toc: true
    toc_depth: 2
  html_document: default
header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading packages
```{r}
suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(formatR))
suppressMessages(library(RColorBrewer))
```

# Loading data
```{r, message=FALSE, warning=FALSE, results= "hide"}
all_dirs <- list.dirs(path = "Data", full.names = TRUE, recursive = F)

list_sample_name <- c("Sample_1", "Sample_2", "Sample_3", "Sample_4")

list_sample <- list()
for (i in 1:length(all_dirs)) {
  
  Seq_raw_file <- Read10X(data.dir = all_dirs[i])
  Seurat_file <- CreateSeuratObject(counts = Seq_raw_file, project = list_sample_name[i], min.cells = 3, min.features =   200)
  list_sample <- append(list_sample, Seurat_file)
}
list_sample

lavage_cells <- merge(list_sample[[1]], y = list_sample[-1], add.cell.ids = c("1","2","3", "4"), project = "bronchoalveolar_lavage")
```

# Quality control
```{r}
lavage_cells[["percent.mt"]] <- PercentageFeatureSet(lavage_cells, pattern = "^MT-")# MT : human cells
VlnPlot(lavage_cells, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.1)
```

# Pre-processing Workfow
```{r, message=FALSE, warning=FALSE, results= "hide"}
# removing low quality cells
lavage_cells <- subset(lavage_cells, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 5) 

# normalizing the data
lavage_cells <- NormalizeData(lavage_cells, normalization.method = "LogNormalize", scale.factor = 10000)

# Feature selection
lavage_cells <- FindVariableFeatures(lavage_cells, selection.method = "vst", nfeatures = 2000) 

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(lavage_cells), 10)

plot1 <- VariableFeaturePlot(lavage_cells)
plot1 <- LabelPoints(plot = plot1, points = 10, repel = T)

# Scaling the data 
all.genes <- rownames(lavage_cells)
lavage_cells <- ScaleData(lavage_cells, features = all.genes)

# Linear dimensional reduction
lavage_cells <- RunPCA(lavage_cells, features = VariableFeatures(object = lavage_cells))
plot2 <- DimPlot(lavage_cells, reduction = "pca")

# Determine the 'dimensionality' of the dataset
lavage_cells <- JackStraw(lavage_cells, num.replicate = 100)
lavage_cells <- ScoreJackStraw(lavage_cells, dims = 1:20)
plot3 <- JackStrawPlot(lavage_cells)
plot4 <- ElbowPlot(lavage_cells, ndims = 20)

lavage_cells <- FindNeighbors(lavage_cells, dims = 1:15)
lavage_cells <- FindClusters(lavage_cells, resolution = 0.5)
lavage_cells <- RunUMAP(lavage_cells, dims = 1:15)
```

```{r, fig.width=12, fig.height=10}
plot1 + plot2 + plot3 + plot4
```

```{r}
lavage_cells@reductions$umap@cell.embeddings[,2] <- -lavage_cells@reductions$umap@cell.embeddings[,2]
lavage_cells@reductions$umap@cell.embeddings[,1] <- -lavage_cells@reductions$umap@cell.embeddings[,1]
```


```{r}
my_palette <- c("#ff9305", "#56B4E9", "#009E73", "#F0E442", "#0072B2",
                "#877f5f", "#CC79A7", "#c0bec2", "#854e07", "#a865eb",
                "#00A087", "#FF9DA7", "#A55AFF", "#8C4B4B", "#00A08E")

DimPlot(lavage_cells, reduction = "umap", cols = my_palette)
```

# Adding cell type to metadata
```{r fig.width=7, fig.height=5}
lavage_cells$personnal_annotation <- lavage_cells$seurat_clusters
levels(lavage_cells$personnal_annotation) <- c(
  "C1 - Alveolar mac",
  "C2 - Alveolar mac",
  "C3 - cMono",
  "C4 - IMo",
  "C5 - Alveolar mac",
  "C6 - LT",
  "C7 - Alveolar mac",
  "C8 - Alveolar mac",
  "C9 - DC",
  "C10 - pDC",
  "C11 - Cycling mac",
  "C12 - Epithelial cells"
)

my_palette <- c("#ff9305", "#56B4E9", "#009E73", "#F0E442", "#0072B2",
                "#877f5f", "#CC79A7", "#c0bec2", "#854e07", "#a865eb",
                "#00A087", "#FF9DA7", "#A55AFF", "#8C4B4B", "#00A08E")

DimPlot(lavage_cells, reduction = "umap", group.by = "personnal_annotation", cols = my_palette)
#ggsave("Umap_annotated.pdf", width = 7, height = 5)
```

# Heatmap clusters
```{r, message=FALSE, warning=FALSE, results= "hide"}
lavage.markers <- FindAllMarkers(lavage_cells, only.pos = TRUE, min.pct = 0.25)

lavage.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10
```

```{r fig.width=8, fig.height=8, message=FALSE, warning=FALSE, results= "hide"}
DoHeatmap(lavage_cells, features = top10$gene, group.colors = my_palette, group.by = "personnal_annotation") + NoLegend() + scale_fill_gradientn(colors = c("blue", "white", "red"))+
  theme(plot.margin = margin(t = 1, r = 4, b = 1, l = 3, unit = "cm"))
#ggsave("Heatmap.clusters.pdf", width = 20, height = 17)
```


# Score Ly6G Macs
Here are the orthologs genes in human of Ly6G Macrophage in mouse
```{r}
top_motro_human <- c("SPP1", "ARG1", "CCL7", "CXCL9", "CCL13", "LGMN", "CCL8", "CTSB","SAA3P", "CCL2", "FABP5", "CTSL", "GATM", "CTSB", "CCL5", "PDPN", "MSR1")
```

```{r fig.width=5, fig.height=5, message=FALSE, warning=FALSE, results= "hide"}
lavage_cells <- AddModuleScore(lavage_cells,
                  features = list(top_motro_human),
                  name="Ly6G_Macro")

FeaturePlot(lavage_cells, features = "Ly6G_Macro1", label = T) +
            scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
#ggsave("ScoreMacro.pdf", width = 5.5, height = 5)
```


```{r}
sessionInfo()
```

