---
title: "Scoring Ly6G Macs Score"
author: "Abinet Joan"
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output:
  pdf_document: 
    toc: true
    toc_depth: 2
  html_document: default
header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading packages
```{r}
suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(formatR))
suppressMessages(library(RColorBrewer))
suppressMessages(library(dittoSeq))
```

# Loading Data
```{r}
cells.combined <- readRDS("../9.1-Loading_BAL_samples/cells.combined_Part1.rds")
```

# Renaming clusters
```{r fig.width=7, fig.height=5, message=FALSE, warning=FALSE, results= "hide"}
cells.combined$Merge_annotation <- cells.combined$seurat_clusters
cells.combined$Merge_annotation <- droplevels(cells.combined$Merge_annotation)

levels(cells.combined$Merge_annotation) <- c("C1 - AM", "C2 - AM", "C3 - AM", "C8 - Mono", "C12 - LT", "C13 - LT", "C9 - Mo-Mac", "C11 - Neutro", "C14 - LT", "C15 - LT", "C16 - LT", "C19 - Epith", "C10 - Mo-DC", "C4 - AM", "C5 - AM", "C6 - AM", "C18 - Mast", "C17 - DC", "C7 - AM")

cells.combined$Merge_annotation <- factor(cells.combined$Merge_annotation, levels = c("C1 - AM", "C2 - AM", "C3 - AM", "C4 - AM", "C5 - AM", "C6 - AM", "C7 - AM", "C8 - Mono", "C9 - Mo-Mac", "C10 - Mo-DC", "C11 - Neutro", "C12 - LT", "C13 - LT", "C14 - LT", "C15 - LT", "C16 - LT", "C17 - DC", "C18 - Mast", "C19 - Epith"))

color_clusters <- c("#0080FF", "#1d1352", "#008000", "#C0C0C0", "#0000FF", "beige", "#FF00FF", "#804000", "#FFFF00", "#008080", "#00FFFF", "#800000", "#FF8000", "#00FF00", "#8000FF", "#80FF00", "#FF0000", "#FF0080", "#000000")

DimPlot(cells.combined, reduction = "umap", group.by = "Merge_annotation", cols = color_clusters)
```

# Heatmap Differential Expression Analysis
```{r, message=FALSE, warning=FALSE, results= "hide"}
Idents(cells.combined) <- "Merge_annotation"
Balf.10x <- FindAllMarkers(cells.combined, only.pos = T, min.pct = 0.25)

Balf.10x %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> top10

Heatmap <- DoHeatmap(cells.combined, features = top10$gene, group.colors = color_clusters, angle	= 80) + NoLegend() + scale_fill_gradientn(colors = c("blue", "white", "red")) 
```

```{r fig.width=15, fig.height=20}
Heatmap
```

# Annotation par patients
```{r}
my_palette <- c("#ff9305", "#56B4E9", "#009E73", "#F0E442", "#0072B2",
                "#877f5f", "#CC79A7")

cells.combined$patient <- cells.combined$orig.ident
cells.combined$patient <- as.factor(cells.combined$patient)
levels(cells.combined$patient) <- c("Patient 1", "Patient 1", "Patient 4", "Patient 6", "Patient 2", "Patient 3", "Patient 5", "Patient 7")

labels_order <- c(1,12,13,14,15,16,17,18,19,2,3,4,5,6,7,8,9,10,11)
dittoBarPlot(cells.combined, "patient", group.by = "Merge_annotation", x.reorder = labels_order, color.panel = my_palette)
#ggsave("barplot_patient.pdf", width = 8, height = 5)
```

# scoring for Ly6G Macs
```{r, message=FALSE, warning=FALSE, results= "hide"}
DefaultAssay(cells.combined) <- "RNA"
top_motro_human <- c("SPP1", "ARG1", "CCL7", "CXCL9", "CCL13", "LGMN", "CCL8", "CTSB","SAA3P", "CCL2", "FABP5", "CTSL", "GATM", "CTSB", "CCL5", "PDPN", "MSR1")

cells.combined <- AddModuleScore(cells.combined,
                  features = list(top_motro_human),
                  name="Ly6G_Macro")
```

```{r fig.width=7, fig.height=5, message=FALSE, warning=FALSE, results= "hide"}
FeaturePlot(cells.combined, features = "Ly6G_Macro1") +
            scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))+ 
            ggtitle("")

```

```{r fig.width=8, fig.height=5, message=FALSE, warning=FALSE, results= "hide"}
VlnPlot(cells.combined, features = "Ly6G_Macro1",  group.by = "Merge_annotation", cols = color_clusters, pt.size = 0)
```

# Saving Data
```{r}
saveRDS(cells.combined, "cells.combined_Part2.rds")
```


```{r}
sessionInfo()
```

