---
title: "Scoring cells"
author: "Abinet Joan"
date: "2023-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
suppressMessages(library(dplyr))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(DESeq2))
suppressMessages(library(readxl))
suppressMessages(library("pheatmap"))
suppressMessages(library("RColorBrewer"))
suppressMessages(library(singscore))
suppressMessages(library(GSEABase))
```


# 
```{r}
annotation_sample <- read_excel("../Data_Thomas/Q3 - publication.xlsx", sheet = "SegmentProperties")
Norm_exprMat <- read_excel("../Data_Thomas/Q3 - publication.xlsx", sheet = "TargetCountMatrix")

Norm_exprMat <- as.data.frame(Norm_exprMat)
rownames(Norm_exprMat) <- Norm_exprMat$TargetName
Norm_exprMat <- Norm_exprMat[,-1]

annotation_sample[8,25] <- "Perilesional"
```


# Get scores for Th1, Th2 and Th17
```{r}
Markers_Th1 <- c("Cxc5", "Ccl3", "Ms4a4b", "Tbx21", "Ifng", "Hopx", "Etv5", "Onecut2")
Markers_Th2 <- c("Gata3", "Il4", "Il17rb", "Nfil3", "Atf5", "Epas1")
Markers_Th17 <- c("Il17a", "Il17f", "Rorc", "Ccr6", "Il23r", "Il22", "Ahr", "Rora")

rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = Markers_Th1)

scoredf <- merge(scoredf, annotation_sample[,c(5,25)], by.x = "row.names", by.y = "SegmentDisplayName")
scoredf <- scoredf[order(scoredf$Group),]

Th1score <- scoredf[,c(1,2,4)]

bp <- barplot(scoredf$TotalScore,
        col = c(rep("green",4), rep("yellow",5) , rep("red",11), rep("cyan",4)),
        
        names.arg = c("1_1","1_2","2_1","2_2","2_12","2_4","2_5","2_6","2_7","1_10", "1_11","1_12", "1_3", "1_4", "1_5", "1_7", "1_8", "2_10", "2_11", "2_9", "1_6","1_9","2_3","2_8"), ylim = c(0,0.3)
)
grid(nx=NA, ny=NULL)
abline(v = bp+0.6, lty=2, col = "gray")

```

```{r}
rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = Markers_Th2)

scoredf <- merge(scoredf, annotation_sample[,c(5,25)], by.x = "row.names", by.y = "SegmentDisplayName")
scoredf <- scoredf[order(scoredf$Group),]

Th2score <- scoredf[,c(1,2,4)]

bp <- barplot(scoredf$TotalScore,
        col = c(rep("green",4), rep("yellow",5) , rep("red",11), rep("cyan",4)),
        
        names.arg = c("1_1","1_2","2_1","2_2","2_12","2_4","2_5","2_6","2_7","1_10", "1_11","1_12", "1_3", "1_4", "1_5", "1_7", "1_8", "2_10", "2_11", "2_9", "1_6","1_9","2_3","2_8"), ylim = c(0,0.3)
)
grid(nx=NA, ny=NULL)
abline(v = bp+0.6, lty=2, col = "gray")

```

```{r}
rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = Markers_Th17)

scoredf <- merge(scoredf, annotation_sample[,c(5,25)], by.x = "row.names", by.y = "SegmentDisplayName")
scoredf <- scoredf[order(scoredf$Group),]

Th17score <- scoredf[,c(1,2,4)]

bp <- barplot(scoredf$TotalScore,
        col = c(rep("green",4), rep("yellow",5) , rep("red",11), rep("cyan",4)),
        
        names.arg = c("1_1","1_2","2_1","2_2","2_12","2_4","2_5","2_6","2_7","1_10", "1_11","1_12", "1_3", "1_4", "1_5", "1_7", "1_8", "2_10", "2_11", "2_9", "1_6","1_9","2_3","2_8")
)
grid(nx=NA, ny=NULL)
abline(v = bp+0.6, lty=2, col = "gray")

```

# dataframe merged
```{r}
df <- cbind(Th1score, Th2score, Th17score)
colnames(df) <- NULL

df <- df[,-c(3,4,6,7,9)]

colnames(df) <- c("ROI", "Th1", "Th2", "Th17")

write.csv(df,"Score_TH.csv")
```



# Markers AT1
```{r}
dir <- "/home/qiang/Documents/Travail_cell/Travail_V3/Cécilia_project_2/Importing_cells/Epithelial_cells/"
markers_AT1 <- read.csv(paste0(dir,"Markers_AT1.csv"))

markers_AT1 <- markers_AT1$X[1:20]

rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = markers_AT1)

scoredf <- merge(scoredf, annotation_sample[,c(5,25)], by.x = "row.names", by.y = "SegmentDisplayName")
scoredf <- scoredf[order(scoredf$Group),]

AT1score <- scoredf[,c(1,2,4)]

bp <- barplot(scoredf$TotalScore,
        col = c(rep("green",4), rep("yellow",5) , rep("red",11), rep("cyan",4)),
        
        names.arg = c("1_1","1_2","2_1","2_2","2_12","2_4","2_5","2_6","2_7","1_10", "1_11","1_12", "1_3", "1_4", "1_5", "1_7", "1_8", "2_10", "2_11", "2_9", "1_6","1_9","2_3","2_8"), ylim = c(0,0.35)
)
grid(nx=NA, ny=NULL)
abline(v = bp+0.6, lty=2, col = "gray")

```

```{r}
dir <- "/home/qiang/Documents/Travail_cell/Travail_V3/Cécilia_project_2/Importing_cells/Epithelial_cells/"
markers_AT2 <- read.csv(paste0(dir,"Markers_AT2.csv"))

markers_AT2 <- markers_AT2$X[1:20]

rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = markers_AT2)

scoredf <- merge(scoredf, annotation_sample[,c(5,25)], by.x = "row.names", by.y = "SegmentDisplayName")
scoredf <- scoredf[order(scoredf$Group),]
AT2score <- scoredf[,c(1,2,4)]

bp <- barplot(scoredf$TotalScore,
        col = c(rep("green",4), rep("yellow",5) , rep("red",11), rep("cyan",4)),
        
        names.arg = c("1_1","1_2","2_1","2_2","2_12","2_4","2_5","2_6","2_7","1_10", "1_11","1_12", "1_3", "1_4", "1_5", "1_7", "1_8", "2_10", "2_11", "2_9", "1_6","1_9","2_3","2_8"), ylim = c(0,0.5)
)
grid(nx=NA, ny=NULL)
abline(v = bp+0.6, lty=2, col = "gray")

```

```{r}
dir <- "/home/qiang/Documents/Travail_cell/Travail_V3/Cécilia_project_2/Importing_cells/Epithelial_cells/"
markers_PAT2 <- read.csv(paste0(dir,"Markers_PrimedAT2.csv"))

markers_PAT2 <- markers_PAT2$X[1:20]

rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = markers_PAT2)

scoredf <- merge(scoredf, annotation_sample[,c(5,25)], by.x = "row.names", by.y = "SegmentDisplayName")
scoredf <- scoredf[order(scoredf$Group),]
PAT2score <- scoredf[,c(1,2,4)]

bp <- barplot(scoredf$TotalScore,
        col = c(rep("green",4), rep("yellow",5) , rep("red",11), rep("cyan",4)),
        
        names.arg = c("1_1","1_2","2_1","2_2","2_12","2_4","2_5","2_6","2_7","1_10", "1_11","1_12", "1_3", "1_4", "1_5", "1_7", "1_8", "2_10", "2_11", "2_9", "1_6","1_9","2_3","2_8"), ylim = c(0,0.5)
)
grid(nx=NA, ny=NULL)
abline(v = bp+0.6, lty=2, col = "gray")
```

```{r}
dir <- "/home/qiang/Documents/Travail_cell/Travail_V3/Cécilia_project_2/Importing_cells/Epithelial_cells/"
markers_DATP <- read.csv(paste0(dir,"Markers_DATP.csv"))

markers_DATP <- markers_DATP$X[1:20]

rankData <- rankGenes(Norm_exprMat)

scoredf <- simpleScore(rankData, upSet = markers_DATP)

scoredf <- merge(scoredf, annotation_sample[,c(5,25)], by.x = "row.names", by.y = "SegmentDisplayName")
scoredf <- scoredf[order(scoredf$Group),]
DATPscore <- scoredf[,c(1,2,4)]

bp <- barplot(scoredf$TotalScore,
        col = c(rep("green",4), rep("yellow",5) , rep("red",11), rep("cyan",4)),
        
        names.arg = c("1_1","1_2","2_1","2_2","2_12","2_4","2_5","2_6","2_7","1_10", "1_11","1_12", "1_3", "1_4", "1_5", "1_7", "1_8", "2_10", "2_11", "2_9", "1_6","1_9","2_3","2_8"), ylim = c(0,0.5)
)
grid(nx=NA, ny=NULL)
abline(v = bp+0.6, lty=2, col = "gray")

```


```{r}
df <- cbind(AT1score, AT2score, DATPscore, PAT2score)
colnames(df) <- NULL

df <- df[,-c(3,4,6,7,9,10,12)]

colnames(df) <- c("ROI", "AT1", "AT2", "DATP", "PrimedAT2")

write.csv(df,"Score_epi.csv")

```

